name = "Rote"
license = "MIT"
licenselink = "https://github.com/rote-docs/rote/blob/master/LICENSE"
description = "A documentation theme for Hugo"
homepage = "https://github.com/rote-docs/rote"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Chris Brower"
  homepage = "https://github.com/idrum4316"
