baseURL = "https://example.org/"
languageCode = "en-us"
title = "Rote Docs"
theme = "rote"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "GitHub Repository"
pre = "<span uk-icon='icon: github'></span>"
url = "https://github.com/rote-docs/rote"
weight = 10