baseURL = "https://example.org/"
languageCode = "en-us"
title = "Hugo UIDocs Theme"
theme = "uidocs"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "GitHub Repository"
pre = "<span uk-icon='icon: github'></span>"
url = "https://github.com/idrum4316/uidocs"
weight = 10